### ISSUE TITLE
Application crash on launch

### ISSUE THREAD

**Issue by dmhl** [Demat/RssReader#6]
Environment: Motorola Moto G, Android 5.1, System language: polish
Branch: develop

Stacktrace below.

 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 14:05:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 14:40:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 14:35:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 12:50:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 02:15:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 05:00:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Fri, 4 Dec 2015 00:30:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Thu, 3 Dec 2015 23:54:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Wed, 2 Dec 2015 17:41:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)
 java.text.ParseException: Unparseable date: "Wed, 2 Dec 2015 20:30:00 +0100" (at offset 0)
     at java.text.DateFormat.parse(DateFormat.java:579)
     at com.android.md.rssreader.sax.RssParseHandler.endElement(RssParseHandler.java:49)
     at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
     at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
     at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
     at com.android.md.rssreader.sax.RssReader.getItems(RssReader.java:34)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:121)
     at com.android.md.rssreader.activiy.MainActivity$AsyncTaskGetRssItems.doInBackground(MainActivity.java:116)
     at android.os.AsyncTask$2.call(AsyncTask.java:292)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)

FATAL EXCEPTION: main
    Process: com.android.md.rssreader, PID: 1675
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
        at java.util.Calendar.setTime(Calendar.java:1195)
        at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:518)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:820)
        at java.text.DateFormat.format(DateFormat.java:314)
        at com.android.md.rssreader.ItemAdapter.getView(ItemAdapter.java:35)
        at android.widget.AbsListView.obtainView(AbsListView.java:2347)
        at android.widget.ListView.measureHeightOfChildren(ListView.java:1270)
        at android.widget.ListView.onMeasure(ListView.java:1182)
        at android.view.View.measure(View.java:17565)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
        at android.support.v7.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5537)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
        at android.view.View.measure(View.java:17565)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2045)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1196)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1409)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Demat** [comment]
probably, the error refers to the os language (settings), working on it.
